"use client";

import { useEffect, useState } from "react";
import { PromptCard, PromptoryShell } from "../../components/PromptoryShell";
import { formatCount, type PromptItem } from "../../lib/prompt-data";

const action = async (body: Record<string, unknown>) => { const response = await fetch("/api/prompts", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (response.status === 401) { window.location.assign(`/auth?returnTo=${encodeURIComponent(window.location.pathname + window.location.search)}`); return; } if (!response.ok) throw new Error("操作失败"); };

export default function AuthorPage({ params }: { params: { name: string } }) {
  const [routeIdentity, setRouteIdentity] = useState(""); const [prompts, setPrompts] = useState<PromptItem[]>([]); const [savedIds, setSavedIds] = useState<(string | number)[]>([]); const [following, setFollowing] = useState(false);
  useEffect(() => { const routeParams = params as unknown as { name?: string } | Promise<{ name: string }>; const apply = (value: string) => setRouteIdentity(decodeURIComponent(value || "")); if (typeof (routeParams as Promise<{ name: string }>).then === "function") (routeParams as Promise<{ name: string }>).then(({ name: value }) => apply(value)); else apply((routeParams as { name?: string }).name || ""); }, [params]);
  useEffect(() => { if (!routeIdentity) return; const stableId = /^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(routeIdentity); const parameter = stableId ? `creatorKey=${encodeURIComponent(routeIdentity)}` : `creator=${encodeURIComponent(routeIdentity)}`; fetch(`/api/prompts?${parameter}&limit=48`).then((response) => response.ok ? response.json() : Promise.reject()).then((data: { prompts?: PromptItem[]; following?: boolean }) => { const items = data.prompts || []; setPrompts(items); setSavedIds(items.filter((item) => item.saved).map((item) => item.id)); setFollowing(Boolean(data.following)); }).catch(() => setPrompts([])); }, [routeIdentity]);
  const toggleSaved = (id: PromptItem["id"]) => { const saved = savedIds.map(String).includes(String(id)); setSavedIds((current) => saved ? current.filter((item) => String(item) !== String(id)) : [...current, id]); action({ action: "save", promptId: id }).catch(() => window.location.reload()); };
  const first = prompts[0]; const displayName = first?.authorName || routeIdentity; const toggleFollow = () => { const next = !following; setFollowing(next); action({ action: "follow", creatorName: displayName, creatorKey: first?.authorId }).catch(() => setFollowing(!next)); };
  const totalSaves = prompts.reduce((sum, item) => sum + (item.saves || 0), 0); const totalViews = prompts.reduce((sum, item) => sum + item.views, 0);
  return <PromptoryShell active="gallery"><div className="content-wrap author-page"><section className="author-hero"><div className="author-avatar">{first?.authorInitials || Array.from(displayName).slice(0, 2).join("") || "创"}</div><div className="author-copy"><p className="eyebrow">CREATOR PROFILE</p><h1>{displayName || "创作者"}<span className="heading-dot">.</span></h1><p>{first?.authorBio || "这位创作者还没有填写个人介绍。"}</p><div><span><strong>{prompts.length}</strong> 条作品</span><span><strong>{formatCount(totalSaves)}</strong> 次收藏</span><span><strong>{formatCount(totalViews)}</strong> 次查看</span></div></div><button className={`button ${following ? "button--light" : "button--dark"}`} onClick={toggleFollow}>{following ? "已关注" : "＋ 关注创作者"}</button></section><div className="section-head author-section-head"><div><span className="section-kicker">PUBLISHED WORKS</span><h2>公开灵感</h2></div><span className="result-count">{prompts.length} 条</span></div>{prompts.length ? <div className="prompt-grid">{prompts.map((item) => <PromptCard key={item.id} item={item} saved={savedIds.map(String).includes(String(item.id))} onToggleSave={toggleSaved} />)}</div> : <div className="empty-state"><div className="empty-icon">✦</div><h3>还没有公开作品</h3><p>创作者发布的提示词会出现在这里。</p><a className="button button--dark" href="/">返回灵感广场</a></div>}</div></PromptoryShell>;
}
